server:
  servlet:
    context-path: /
  port: 8081


spring:
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.168.10.118:1521:orcl
      username: bvis
      password: bvis123
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 30000
        validation-query: SELECT 1 FROM DUAL
        keep-alive: true
        keep-alive-between-time-millis: 66000
        test-on-borrow: true
        test-on-return: false
        test-while-idle: true
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.jdbc: info
    #    org.hibernate: debug
    org.mybatis: info
    org.druid: info
